version: '3'
services:
  db: 
    container_name: sample-python-mysql-db
    build: ./db
    ports: 
      - "3306:3306"
    tty: true
    restart: always
    volumes:
      - sample-db-volume:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TZ

  web:
    container_name: sample-python-web
    build: ./app
    ports: 
      - "1323:1323"
    privileged: true
    volumes:
      - ./app:/app
    restart: always
    tty: true
    links:
      - db
    depends_on:
      - db
volumes:
  sample-db-volume: